### ISSUE TITLE
トークンのIdentifierTypeで正しい型を取得できない

### ISSUE THREAD

**Issue by raylicola** [mimosa-project/mizcore#30]
# 内容
トークンテーブルの各トークンが返す IdentifierType の型に誤りがある

# 再現方法
```py
from py_miz_controller import MizController

miz_controller = MizController()
miz_controller.exec_file(mizファイルパス, vctファイルパス)
token_table = miz_controller.token_table

token = token_table.token(i)
token.identifier_type
```

# 検証結果
| #   | 検証ファイル | 行 | トークン           | IdentifierType 想定 | 実際の返り値 | 
| :-: | :---------: | :---: | :----------------: | :-----------------: | :-----------------: | 
| 1   | tarski_0     | 19 | x, y, z, a         | RESERVED            | LABEL               | 
| 2   | tarski_0     | 24 | x                  | VARIABLE            | LABEL               | 
| 3   | tarski_0     | 48 | Replacement        | SCHEME              | LABEL               | 
| 4   | tarski_0     | 48 | A                  | FUNCTOR             | LABEL               | 
| 5   | tarski_0     | 48 | P                  | PREDICATE           | LABEL               | 
| 6   | numerals   | 36, 37 | ORDINAL1, SUBSET_1 | FILENAME            | UNKNOWN            | 

tarski_0
```
#1
reserve x,y,z,a for object;

#2
theorem
  for x being object holds x is set;

#3, #4, #5
scheme Replacement { A() -> set, P[object, object] }:
  ex X st for x holds x in X iff ex y st y in A() & P[y,x]
 
```

numerals
```
#6
proof
  {} in omega by ORDINAL1:def 11;
  hence thesis by SUBSET_1:def 1;
```

**Comment by aabaa** [comment]
| #   | 検証ファイル | 行 | トークン           | IdentifierType 想定 | 実際の返り値 | 
| :-: | :---------: | :---: | :----------------: | :-----------------: | :-----------------: | 
| 1   | tarski_0     | 19 | x, y, z, a         | RESERVED            | LABEL               | 
| 2   | tarski_0     | 24 | x                  | VARIABLE            | LABEL               | 
| 3   | tarski_0     | 48 | Replacement        | SCHEME              | LABEL               | 
| 4   | tarski_0     | 48 | A                  | FUNCTOR             | LABEL               | 
| 5   | tarski_0     | 48 | P                  | PREDICATE           | LABEL               | 
| 6   | numerals   | 36, 37 | ORDINAL1, SUBSET_1 | FILENAME            | UNKNOWN            | 

の2と6を修正した．その他は以前から正しく動作している．
